### ISSUE TITLE
Bignums, big problem

### ISSUE THREAD

**Issue by jasonhemann** [michaelballantyne/faster-miniKanren#11]
@gregr pointed out that numbers may get big enough that `eq?` is no longer sufficient or correct. Such bugs would be especially pernicious, because they would only rarely manifest, and only on long-running or large programs. He suggests switching to bignum-accepting `eqv?` where numeric comparisons occur.

**Comment by michaelballantyne** [comment]
I don't think we rely on eq? for numeric equality anywhere. In unify there's a fallback to equal? as the final case. Variables contain a numeric `idx`, but variable equality works by pointer equality of the vectors allocated to represent variables, not by equality of the `idx`. Let me know if there's something I missed, though!

**Comment by gregr** [comment]
The bignum-vulnerable use of `eq?` we saw during the hackathon was probably removed during refactoring.

The only one left is due to using a `hasheq` for the intmap:
https://github.com/michaelballantyne/faster-miniKanren/blob/master/mk.rkt#L16

It's not likely to cause an issue anytime soon, but if you leave a long-running program for long enough and it doesn't consume all of your memory, I suppose you'll hit this.

**Comment by michaelballantyne** [comment]
Ah, okay. There is a remaining `eq?` indeed. I still don't think it could cause a problem though. The var-idx is only computed once on allocating the object. So long as the var we insert and the var we look up are the same object, the var-idxs will also be the same values.

**Comment by gregr** [comment]
That's a good point.  These bignums should only have the same numeric value when they are also the same one allocated in memory.
